version: '3.3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      PORT: '${PORT}'
      REDIS_URL: '${REDIS_URL}'
      DATABASE_KEY: '${DATABASE_KEY}'
      ACCESS_SECRET: '${ACCESS_SECRET}'
      REFRESH_SECRET: '${REFRESH_SECRET}'
      MAIL_SECRET: '${MAIL_SECRET}'
      EMAIL_ID: '${EMAIL_ID}'
      EMAIL_PASS: '${EMAIL_PASS}'
    links:
      - redis
      # - proxy
    volumes:
      - /home/${HOME_DIR}/Documents/swap-books-front/images:/usr/src/app/images
  redis:
    container_name: cache
    image: redis:6.2
    restart: always
    expose:
      - 6379
    volumes:
      - redis-data:/data
  # proxy:
  #   container_name: nginx-proxy
  #   image: nginx:1.19
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  redis-data:
    driver: local
