export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH';
export const AUTH_REDIRECT_START = 'AUTH_REDIRECT_START';
export const AUTH_REDIRECT_SUCCESS = 'AUTH_REDIRECT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ERROR_REFRESH = 'AUTH_ERROR_REFRESH';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const CREATE_USER_REFRESH = 'CREATE_USER_REFRESH';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const VERIFY_EMAIL_START = 'VERIFY_EMAIL_START';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL';

export const UPDATE_USER_LOC_START = 'UPDATE_USER_LOC_START';
export const UPDATE_USER_LOC_SUCCESS = 'UPDATE_USER_LOC_SUCCESS';
export const UPDATE_USER_LOC_FAIL = 'UPDATE_USER_LOC_FAIL';

export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_MORE_BOOKS_SUCCESS = 'FETCH_MORE_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';
export const BOOKS_RESET_TO_NIL = 'BOOKS_RESET_TO_NIL';

export const ADD_A_BOOK_START = 'ADD_A_BOOK_START';
export const ADD_A_BOOK_SUCCESS = 'ADD_A_BOOK_SUCCESS';
export const ADD_A_BOOK_FAIL = 'ADD_A_BOOK_FAIL';
export const ADD_A_BOOK_REFRESH = 'ADD_A_BOOK_REFRESH';

export const EXPRESS_INTEREST_START = 'EXPRESS_INTEREST_START';
export const EXPRESS_INTEREST_SUCCESS = 'EXPRESS_INTEREST_SUCCESS';
export const EXPRESS_INTEREST_FAIL = 'EXPRESS_INTEREST_FAIL';

export const MAKE_UNAVAILABLE_START = 'MAKE_UNAVAILABLE_START';
export const MAKE_UNAVAILABLE_SUCCESS = 'MAKE_UNAVAILABLE_SUCCESS';
export const MAKE_UNAVAILABLE_FAIL = 'MAKE_UNAVAILABLE_FAIL';

export const AVAILABLE_TEN_MORE_DAYS_START = 'AVAILABLE_TEN_MORE_DAYS_START';
export const AVAILABLE_TEN_MORE_DAYS_SUCCESS = 'AVAILABLE_TEN_MORE_DAYS_SUCCESS';
export const AVAILABLE_TEN_MORE_DAYS_FAIL = 'AVAILABLER_TEN_MORE_DAYS_FAIL';
export const AVAILABLE_TEN_MORE_DAYS_REFRESH = 'AVAILABLE_TEN_MORE_DAYS_REFRESH';

export const GET_NOTIFICATIONS_START = 'GET_NOTIFICATIONS_START';
export const GET_INITIAL_NOTIFICATIONS_SUCCESS = 'GET_INITIAL_NOTIFICATIONS_SUCCESS';
export const GET_MORE_NOTIFICATIONS_SUCCESS = 'GET_MORE_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';
export const ADD_LIVE_NOTIFICATION = 'ADD_LATEST_NOTIFICATION';
export const SET_NOTIFICATION_AS_SEEN = 'SET_NOTIFICATION_AS_SEEN';

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const FETCH_ACTIVE_ROOMS_START = 'FETCH_ACTIVE_ROOMS_START';
export const FETCH_ACTIVE_ROOMS_SUCCESS = 'FETCH_ACTIVE_ROOMS_SUCCESS';
export const FETCH_ACTIVE_ROOMS_FAIL = 'FETCH_ACTIVE_ROOMS_FAIL';

export const JOIN_SINGLE_ROOM = 'JOIN_SINGLE_ROOM';
export const LEAVE_SINGLE_ROOM = 'LEAVE_SINGLE_ROOM';

export const FETCH_ROOM_MESSAGE_START = 'FETCH_ROOM_MESSAGE_START';
export const FETCH_ROOM_MESSAGE_SUCCESS = 'FETCH_ROOM_MESSAGE_SUCCESS';
export const FETCH_ROOM_MESSAGE_FAIL = 'FETCH_ROOM_MESSAGE_FAIL';
export const ADD_ROOM_MESSAGE_SUCCESS = 'ADD_ROOM_MESSAGE_SUCCESS';
export const ADD_NONACTIVE_ROOM_UNREAD_MSG_NOTIFICATION =
  'ADD_NONACTIVE_ROOM_UNREAD_MSG_NOTIFICATION';
export const REGISTER_SENT_MESSAGE_SUCCESS = 'REGISTER_SENT_MESSAGE_SUCCESS';
export const SET_MESSAGE_AS_SEEN_SUCCESS = 'SET_MESSAGE_AS_SEEN_SUCCESS';

export const CLOSE_MESSAGE_BOX = 'CLOSE_MESSAGE_BOX';
export const OPEN_MESSAGE_BOX = 'OPEN_MESSAGE_BOX';
export const SET_MESSAGE_BOX = 'SET_MESSAGE_BOX';

export const FORGOT_PASS_START = 'FORGOT_PASS_START';
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS';
export const FORGOT_PASS_FAIL = 'FORGOT_PASS_FAIL';

export const RESET_PASS_START = 'RESET_PASS_START';
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_FAIL = 'RESET_PASS_FAIL';
