export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const UPDATE_USER_LOC_START = 'UPDATE_USER_LOC_START';
export const UPDATE_USER_LOC_SUCCESS = 'UPDATE_USER_LOC_SUCCESS';
export const UPDATE_USER_LOC_FAIL = 'UPDATE_USER_LOC_FAIL';

export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';

export const ADD_A_BOOK_START = 'ADD_A_BOOK_START';
export const ADD_A_BOOK_SUCCESS = 'ADD_A_BOOK_SUCCESS';
export const ADD_A_BOOK_FAIL = 'ADD_A_BOOK_FAIL';

export const EXPRESS_INTEREST_START = 'EXPRESS_INTEREST_START';
export const EXPRESS_INTEREST_SUCCESS = 'EXPRESS_INTEREST_SUCCESS';
export const EXPRESS_INTEREST_FAIL = 'EXPRESS_INTEREST_FAIL';

export const GET_NOTIFICATIONS_START = 'GET_NOTIFICATIONS_START';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';
export const ADD_LATEST_NOTIFICATION = 'ADD_LATEST_NOTIFICATION';
export const SET_NOTIFICATION_AS_SEEN = 'SET_NOTIFICATION_AS_SEEN';

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const FETCH_ACTIVE_ROOMS_START = 'FETCH_ACTIVE_ROOMS_START';
export const FETCH_ACTIVE_ROOMS_SUCCESS = 'FETCH_ACTIVE_COVERSATIONS_SUCCESS';
export const FETCH_ACTIVE_ROOMS_FAIL = 'FETCH_ACTIVE_COVERSATIONS_FAIL';

export const FETCH_ROOM_MESSAGE_START = 'FETCH_ROOM_MESSAGE_START';
export const FETCH_ROOM_MESSAGE_SUCCESS = 'FETCH_ROOM_MESSAGE_SUCCESS';
export const FETCH_ROOM_MESSAGE_FAIL = 'FETCH_ROOM_MESSAGE_FAIL';

export const CLOSE_MESSAGE_BOX = 'CLOSE_MESSAGE_BOX';
export const OPEN_MESSAGE_BOX = 'OPEN_MESSAGE_BOX';
export const SET_MESSAGE_BOX = 'SET_MESSAGE_BOX';
