export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';

export const ADD_A_BOOK_START = 'ADD_A_BOOK_START';
export const ADD_A_BOOK_SUCCESS = 'ADD_A_BOOK_SUCCESS';
export const ADD_A_BOOK_FAIL = 'ADD_A_BOOK_FAIL';

export const EXPRESS_INTEREST_START = 'EXPRESS_INTEREST_START';
export const EXPRESS_INTEREST_SUCCESS = 'EXPRESS_INTEREST_SUCCESS';
export const EXPRESS_INTEREST_FAIL = 'EXPRESS_INTEREST_FAIL';

export const GET_NOTIFICATIONS_START = 'GET_NOTIFICATIONS_START';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';

export const FETCH_BOOKS_VISITING_PROFILE_START =
  'FETCH_BOOKS_VISITING_PROFILE_START';
export const FETCH_BOOKS_VISITING_PROFILE_SUCCESS =
  'FETCH_BOOKS_VISITING_PROFILE_SUCCESS';
export const FETCH_BOOKS_VISITING_PROFILE_FAIL = 'FETCH_BOOKS_VISITING_PROFILE_FAIL';

export const FETCH_USER_VISITING_PROFILE_START = 'FETCH_USER_VISITING_PROFILE_START';
export const FETCH_USER_VISITING_PROFILE_SUCCESS =
  'FETCH_VISITING_PROFILE_USER_SUCCESS';
export const FETCH_USER_VISITING_PROFILE_FAIL = 'FETCH_USER_VISITING_PROFILE_FAIL';
